services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_docs_management
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend_network
  test_database:
    image: "postgres:latest"
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: test_admin
      POSTGRES_PASSWORD: test_admin
      POSTGRES_DB: user_docs_management
  pgadmin:
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    networks:
      - backend_network
networks:
  backend_network:
    driver: bridge
